require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/appointment_titles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AppointmentTitle. As you add validations to AppointmentTitle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AppointmentTitle.create! valid_attributes
      get appointment_titles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      appointment_title = AppointmentTitle.create! valid_attributes
      get appointment_title_url(appointment_title)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_appointment_title_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      appointment_title = AppointmentTitle.create! valid_attributes
      get edit_appointment_title_url(appointment_title)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AppointmentTitle" do
        expect {
          post appointment_titles_url, params: { appointment_title: valid_attributes }
        }.to change(AppointmentTitle, :count).by(1)
      end

      it "redirects to the created appointment_title" do
        post appointment_titles_url, params: { appointment_title: valid_attributes }
        expect(response).to redirect_to(appointment_title_url(AppointmentTitle.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AppointmentTitle" do
        expect {
          post appointment_titles_url, params: { appointment_title: invalid_attributes }
        }.to change(AppointmentTitle, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post appointment_titles_url, params: { appointment_title: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested appointment_title" do
        appointment_title = AppointmentTitle.create! valid_attributes
        patch appointment_title_url(appointment_title), params: { appointment_title: new_attributes }
        appointment_title.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the appointment_title" do
        appointment_title = AppointmentTitle.create! valid_attributes
        patch appointment_title_url(appointment_title), params: { appointment_title: new_attributes }
        appointment_title.reload
        expect(response).to redirect_to(appointment_title_url(appointment_title))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        appointment_title = AppointmentTitle.create! valid_attributes
        patch appointment_title_url(appointment_title), params: { appointment_title: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested appointment_title" do
      appointment_title = AppointmentTitle.create! valid_attributes
      expect {
        delete appointment_title_url(appointment_title)
      }.to change(AppointmentTitle, :count).by(-1)
    end

    it "redirects to the appointment_titles list" do
      appointment_title = AppointmentTitle.create! valid_attributes
      delete appointment_title_url(appointment_title)
      expect(response).to redirect_to(appointment_titles_url)
    end
  end
end
